// flow-typed signature: 91437c4e2e77c5de4ddbdaf73df5a9e6
// flow-typed version: <<STUB>>/react-string-replace_v^0.4.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-string-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-string-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-string-replace/index' {
  declare module.exports: $Exports<'react-string-replace'>;
}
declare module 'react-string-replace/index.js' {
  declare module.exports: $Exports<'react-string-replace'>;
}
