// flow-typed signature: ecf21423cef084987fbb7b6224f74bee
// flow-typed version: <<STUB>>/webpack-eslint-plugin_v^1.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-eslint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-eslint-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-eslint-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-eslint-plugin/lib/index.js' {
  declare module.exports: $Exports<'webpack-eslint-plugin/lib/index'>;
}
declare module 'webpack-eslint-plugin/src/index.js' {
  declare module.exports: $Exports<'webpack-eslint-plugin/src/index'>;
}
